### ISSUE TITLE
Add support for package.json not at the root directory

### ISSUE THREAD

**Issue by daprahamian** [ralphtheninja/version-changed#3]
I'm currently dealing with a repository where the package.json is not at the root directory. When I run `npx version-changed`, I get the following output:

```
Error: Command failed: git show HEAD:package.json
fatal: Path 'bindings/node/package.json' exists, but not 'package.json'.
Did you mean 'HEAD:bindings/node/package.json' aka 'HEAD:./package.json'?
```

Can this be changed to either use the relative path to `package.json` (`git show HEAD:./package.json`) or allow some sort of configuration to point to the `package.json`?

**Comment by ralphtheninja** [comment]
PR welcome :)
